### PR TITLE
Jonathan Pull Request

### PR DESCRIPTION
**Pull request by jcheung4**
Added jonathan.py and modified collect_images.py accordingly.

### CODE REVIEW

**Review by kellyhpark — COMMENTED** [review]
Please be sure to include the img_data.yaml file, and jonathan_images folder in the data folder. Currently, running produces FileNotFoundError for img_data.yaml.

**Comment by Derek-Wen** [comment]
I'm receiving the same problem as Kelly. Maybe you can either include the file(s) or update the README.md to describe how someone can obtain it themselves.

**Review by Derek-Wen — CHANGES_REQUESTED** [review]
NOTE: SORRY I accidently requested a change instead of a comment and I don't know how to delete it

I'm receiving the same problem as Kelly. Maybe you can either include the file(s) or update the README.md to describe how someone can obtain it themselves.

**Comment by jcheung4** [comment]
In the collect_images.py file, I specified a specific folder to save my images within the data folder in case of some naming issues, though this is probably unnecessary. I added the new folder on my end though it does not show up when I push because its an empty directory.

**Review by pdashk — APPROVED** [review]

**Comment by pdashk** [comment]
code needs to create `jonathan_images` folder or else will get error. will resolve in my commit to resolve merge conflicts

**Pull request merged**
