### PR TITLE
kevin.py

### PR DESCRIPTION
**Pull request by Kevinbui2**
Added kevin.py script to pull Kevin's images

### CODE REVIEW

**Comment by pdashk** [comment]
please remove .DS_STORE files

**Comment by pdashk** [comment]
- Load `structures_info.json` to our joint SharePoint
- Please modify README.md to note where to find `structures_info.json`.

**Comment by sunwoo604** [comment]
It works for me.

**Review by pdashk — APPROVED** [review]
works fine. should load images to data/images (no kevin folder). will accept and modify later

**Pull request merged**
